###
GET http://localhost:3000

###
GET http://localhost:3000/health

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "yazid",
    "username": "yazid1",
    "password": "123",
    "role": "09bd8bf8-1e18-4b5b-8512-421ce45ff18e"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "yazid",
    "password": "123"
}

###
GET http://localhost:3000/me
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE0NjcyMWVhLTQwNjAtNDU4OC1hNjE4LWU5Y2M1NWIzZTA4ZCIsImlhdCI6MTY2NzE4OTI3NCwiZXhwIjoxNjY3MTg5MzM0fQ.-tC-94EtHCZiq9BLjHBSP3am73enAgJfYll2eDaD7Zk

###
GET http://localhost:3000/role

###
GET http://localhost:3000/api-manager

###
POST http://localhost:3000/api-manager/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE0NjcyMWVhLTQwNjAtNDU4OC1hNjE4LWU5Y2M1NWIzZTA4ZCIsImlhdCI6MTY2NzE4OTMxOSwiZXhwIjoxNjY3MTg5Mzc5fQ.DWaq6f2pc0PypITJFow-Do6pVI9G1YlhvpMmtUIgwn0

{
    "url": "https://haloyazid.com",
    "author": "Yazid",
    "description": "ini adalah deskripsi api",
    "categories": ["pendidikan", "API", "Test", "TEST2", "AAA"]
}

###
PUT  http://localhost:3000/api-manager/update/64f8964d-f16b-4c17-b121-d91ddc823a30
Content-Type: application/json

{
    "url": "http://google.com",
    "status": "TIDAK_AKTIF",
    "author": "orang",
    "categories": ["test", "pendidikan"]
}

###
DELETE http://localhost:3000/api-manager/delete/c4a3361d-849e-45c2-9c55-467e59a35afb