###
GET http://localhost:3000

###
GET http://localhost:3000/health

###
POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "yazid",
    "username": "yazid1",
    "password": "123",
    "role": "09bd8bf8-1e18-4b5b-8512-421ce45ff18e"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123"
}

###
DELETE http://localhost:3000/logout

###
GET http://localhost:3000/me

###
GET http://localhost:3000/role

###
GET http://localhost:3000/api-manager

###
POST http://localhost:3000/api-manager/add
Content-Type: application/json

{
    "name": "google 1",
    "url": "https://haloyazid.com",
    "author": "Yazid",
    "description": "ini adalah deskripsi api",
    "categories": ["google"]
}

###
PUT  http://localhost:3000/api-manager/update/64f8964d-f16b-4c17-b121-d91ddc823a30
Content-Type: application/json

{
    "url": "http://google.com",
    "status": "TIDAK_AKTIF",
    "author": "orang",
    "categories": ["test", "pendidikan"]
}

###
DELETE http://localhost:3000/api-manager/delete/a7032208-f005-4e9e-bc92-081d04f40d6b